# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: nbd_mongo
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nbd
      MONGO_INITDB_ROOT_PASSWORD: nbdpassword


  redis-stack:
    image: redis/redis-stack
    volumes:
      - redis-stack-data:/bitnami/redis/data
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - redisnet

volumes:
  redis-stack-data:
    driver: local

networks:
  mongonet: {}
  redisnet: {}